### ISSUE TITLE
Failed to run test.py after installation

### ISSUE THREAD

**Issue by lingvisa** [howl-anderson/Chinese_models_for_SpaCy#24]
I had similar problem of running the test.py and those are my versions of dependencies:
zh_core_web_sm-2.0.5
python: 3.7.5
jieba==0.42
more-itertools==8.1.0
murmurhash==1.0.2
numpy==1.18.1
plac==1.1.3
preshed==3.0.2
requests==2.22.0
spacy==2.2.3
thinc==7.3.1
zh-core-web-sm==2.0.5

I am on Mac Pro. In the requirements.txt, it doesn't specify the specific versions of dependencies. I afraid it may be due to different versions of spacy and thinc.

@howl-anderson can you please specify what versions of dependencies are required in order for it to work correctly for the test demo?

python3 ./test.py
Traceback (most recent call last):
File "./test.py", line 7, in
nlp = zh_core_web_sm.load()
File "/Users/congminmin/nlp/my-env/chinese/lib/python3.7/site-packages/zh_core_web_sm/init.py", line 12, in load
return load_model_from_init_py(file, **overrides)
File "/Users/congminmin/nlp/my-env/chinese/lib/python3.7/site-packages/spacy/util.py", line 228, in load_model_from_init_py
return load_model_from_path(data_path, meta, **overrides)
File "/Users/congminmin/nlp/my-env/chinese/lib/python3.7/site-packages/spacy/util.py", line 211, in load_model_from_path
return nlp.from_disk(model_path)
File "/Users/congminmin/nlp/my-env/chinese/lib/python3.7/site-packages/spacy/language.py", line 941, in from_disk
util.from_disk(path, deserializers, exclude)
File "/Users/congminmin/nlp/my-env/chinese/lib/python3.7/site-packages/spacy/util.py", line 654, in from_disk
reader(path / key)
File "/Users/congminmin/nlp/my-env/chinese/lib/python3.7/site-packages/spacy/language.py", line 936, in
p, exclude=["vocab"]
File "pipes.pyx", line 661, in spacy.pipeline.pipes.Tagger.from_disk
File "/Users/congminmin/nlp/my-env/chinese/lib/python3.7/site-packages/spacy/util.py", line 654, in from_disk
reader(path / key)
File "pipes.pyx", line 641, in spacy.pipeline.pipes.Tagger.from_disk.load_model
File "pipes.pyx", line 643, in spacy.pipeline.pipes.Tagger.from_disk.load_model
File "/Users/congminmin/nlp/my-env/chinese/lib/python3.7/site-packages/thinc/neural/_classes/model.py", line 376, in from_bytes
copy_array(dest, param[b"value"])
File "/Users/congminmin/nlp/my-env/chinese/lib/python3.7/site-packages/thinc/neural/util.py", line 145, in copy_array
dst[:] = src
ValueError: could not broadcast input array from shape (128) into shape (96)

**Comment by czcz1024** [comment]
同问

**Comment by howl-anderson** [comment]
这个基本属于常见问题了，这个问题是 SpaCy 自身造成的，建议你们重装环境尝试

**Comment by lingvisa** [comment]
@howl-anderson 你有一组依赖的 reversion numbers 可以让这个跑起来吗？现在下载的 spacy 总是出这个问题。

**Comment by howl-anderson** [comment]
额，已经很久没有投入这个项目，相关的环境找不到了，你应该用上一个版本的 SpaCy，新版本 API 改变了

**Comment by howl-anderson** [comment]
@lingvisa @czcz1024 Chinese model for SpaCy 2.2.x already released, it should fix this issue. Feel free to try it.
