### ISSUE TITLE
运行test.py失败

### ISSUE THREAD

**Issue by lucas-acc** [howl-anderson/Chinese_models_for_SpaCy#8]
`bogon:研报 pupil$ python test.py 
Building prefix dict from the default dictionary ...
Loading model from cache /var/folders/5q/_s76xf495kb0pxqx0ntj89b40000gn/T/jieba.cache
Loading model cost 0.645 seconds.
Prefix dict has been built succesfully.
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    main()
  File "test.py", line 10, in main
    doc = nlp("王小明在北京的清华大学读书")
  File "/Users/pupil/anaconda3/lib/python3.6/site-packages/spacy/language.py", line 341, in __call__
    doc = proc(doc)
  File "nn_parser.pyx", line 337, in spacy.syntax.nn_parser.Parser.__call__
  File "nn_parser.pyx", line 400, in spacy.syntax.nn_parser.Parser.parse_batch
  File "nn_parser.pyx", line 724, in spacy.syntax.nn_parser.Parser.get_batch_model
  File "/Users/pupil/anaconda3/lib/python3.6/site-packages/thinc/api.py", line 61, in begin_update
    X, inc_layer_grad = layer.begin_update(X, drop=drop)
  File "/Users/pupil/anaconda3/lib/python3.6/site-packages/thinc/api.py", line 280, in begin_update
    drop=drop)
  File "/Users/pupil/anaconda3/lib/python3.6/site-packages/thinc/api.py", line 61, in begin_update
    X, inc_layer_grad = layer.begin_update(X, drop=drop)
  File "/Users/pupil/anaconda3/lib/python3.6/site-packages/thinc/api.py", line 374, in uniqued_fwd
    Y_uniq, bp_Y_uniq = layer.begin_update(X_uniq, drop=drop)
  File "/Users/pupil/anaconda3/lib/python3.6/site-packages/thinc/api.py", line 61, in begin_update
    X, inc_layer_grad = layer.begin_update(X, drop=drop)
  File "/Users/pupil/anaconda3/lib/python3.6/site-packages/thinc/neural/_classes/layernorm.py", line 51, in begin_update
    X, backprop_child = self.child.begin_update(X, drop=0.)
  File "/Users/pupil/anaconda3/lib/python3.6/site-packages/thinc/neural/_classes/maxout.py", line 69, in begin_update
    output__boc = self.ops.batch_dot(X__bi, W)
  File "ops.pyx", line 338, in thinc.neural.ops.NumpyOps.batch_dot
ValueError: shapes (7,512) and (640,384) not aligned: 512 (dim 1) != 640 (dim 0)
bogon:研报 pupil$ 
`

**Comment by howl-anderson** [comment]
What version of zh_core_web_sm can reproduce this issue?

**Comment by lucas-acc** [comment]
谢谢您的回复，zh_core_web_sm-2.0.4。

**Comment by eshen89** [comment]
Hi, I have the same error when trying to run ./test.py
`
Building prefix dict from the default dictionary ...
Loading model from cache /var/folders/0q/qg92npw945sc7wz_gcd3th8w0000gn/T/jieba.cache
Loading model cost 0.994 seconds.
Prefix dict has been built succesfully.
Traceback (most recent call last):
  File "./test.py", line 22, in <module>
    main()
  File "./test.py", line 11, in main
    doc = nlp("王小明在北京的清华大学读书")
  File "/usr/local/lib/python3.6/site-packages/spacy/language.py", line 333, in __call__
    doc = proc(doc)
  File "pipeline.pyx", line 390, in spacy.pipeline.Tagger.__call__
  File "pipeline.pyx", line 402, in spacy.pipeline.Tagger.predict
  File "/usr/local/lib/python3.6/site-packages/thinc/neural/_classes/model.py", line 161, in __call__
    return self.predict(x)
  File "/usr/local/lib/python3.6/site-packages/thinc/api.py", line 55, in predict
    X = layer(X)
  File "/usr/local/lib/python3.6/site-packages/thinc/neural/_classes/model.py", line 161, in __call__
    return self.predict(x)
  File "/usr/local/lib/python3.6/site-packages/thinc/api.py", line 293, in predict
    X = layer(layer.ops.flatten(seqs_in, pad=pad))
  File "/usr/local/lib/python3.6/site-packages/thinc/neural/_classes/model.py", line 161, in __call__
    return self.predict(x)
  File "/usr/local/lib/python3.6/site-packages/thinc/api.py", line 55, in predict
    X = layer(X)
  File "/usr/local/lib/python3.6/site-packages/thinc/neural/_classes/model.py", line 161, in __call__
    return self.predict(x)
  File "/usr/local/lib/python3.6/site-packages/thinc/neural/_classes/model.py", line 125, in predict
    y, _ = self.begin_update(X)
  File "/usr/local/lib/python3.6/site-packages/thinc/api.py", line 374, in uniqued_fwd
    Y_uniq, bp_Y_uniq = layer.begin_update(X_uniq, drop=drop)
  File "/usr/local/lib/python3.6/site-packages/thinc/api.py", line 61, in begin_update
    X, inc_layer_grad = layer.begin_update(X, drop=drop)
  File "/usr/local/lib/python3.6/site-packages/thinc/neural/_classes/layernorm.py", line 51, in begin_update
    X, backprop_child = self.child.begin_update(X, drop=0.)
  File "/usr/local/lib/python3.6/site-packages/thinc/neural/_classes/maxout.py", line 69, in begin_update
    output__boc = self.ops.batch_dot(X__bi, W)
  File "ops.pyx", line 338, in thinc.neural.ops.NumpyOps.batch_dot
ValueError: shapes (7,512) and (640,384) not aligned: 512 (dim 1) != 640 (dim 0)
`
zh_core_web_sm-2.0.5 is being used. Thanks

**Comment by howl-anderson** [comment]
Try reinstall the spacy. Someone reported it works.

**Comment by eshen89** [comment]
Thank you for your reply!
May I know the environment of the working case?

Mine is:
MacOS 10.13.6
Python verison-3.6.6

Much appreciate

**Comment by howl-anderson** [comment]
Does the reinstall don't work? Maybe it's related to thinc library which is a dependency of SpaCy. You can try to install all the dependencies from a blank virtualenv environment.

**Comment by lingvisa** [comment]
I had similar problem and those versions:
zh_core_web_sm-2.0.5
python: 3.7.5
jieba==0.42
more-itertools==8.1.0
murmurhash==1.0.2
numpy==1.18.1
plac==1.1.3
preshed==3.0.2
requests==2.22.0
spacy==2.2.3
thinc==7.3.1
zh-core-web-sm==2.0.5

I am on Mac Pro. In the requirements.txt, it doesn't specify the specific versions of dependencies. I afraid it may be due to different versions of spacy and thinc.
@howl-anderson can you please specify what versions of dependencies are required in order for it to work correctly for the test demo?

 


python3 ./test.py 
Traceback (most recent call last):
  File "./test.py", line 7, in <module>
    nlp = zh_core_web_sm.load()
  File "/Users/congminmin/nlp/my-env/chinese/lib/python3.7/site-packages/zh_core_web_sm/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/Users/congminmin/nlp/my-env/chinese/lib/python3.7/site-packages/spacy/util.py", line 228, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/Users/congminmin/nlp/my-env/chinese/lib/python3.7/site-packages/spacy/util.py", line 211, in load_model_from_path
    return nlp.from_disk(model_path)
  File "/Users/congminmin/nlp/my-env/chinese/lib/python3.7/site-packages/spacy/language.py", line 941, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "/Users/congminmin/nlp/my-env/chinese/lib/python3.7/site-packages/spacy/util.py", line 654, in from_disk
    reader(path / key)
  File "/Users/congminmin/nlp/my-env/chinese/lib/python3.7/site-packages/spacy/language.py", line 936, in <lambda>
    p, exclude=["vocab"]
  File "pipes.pyx", line 661, in spacy.pipeline.pipes.Tagger.from_disk
  File "/Users/congminmin/nlp/my-env/chinese/lib/python3.7/site-packages/spacy/util.py", line 654, in from_disk
    reader(path / key)
  File "pipes.pyx", line 641, in spacy.pipeline.pipes.Tagger.from_disk.load_model
  File "pipes.pyx", line 643, in spacy.pipeline.pipes.Tagger.from_disk.load_model
  File "/Users/congminmin/nlp/my-env/chinese/lib/python3.7/site-packages/thinc/neural/_classes/model.py", line 376, in from_bytes
    copy_array(dest, param[b"value"])
  File "/Users/congminmin/nlp/my-env/chinese/lib/python3.7/site-packages/thinc/neural/util.py", line 145, in copy_array
    dst[:] = src
**_ValueError: could not broadcast input array from shape (128) into shape (96)_**
