### ISSUE TITLE
zh_core_web_sm-2.0.5.tar.gz   OSError: [E050] Can't find model 'zh_model.vectors'. 

### ISSUE THREAD

**Issue by Gaozhen0816** [howl-anderson/Chinese_models_for_SpaCy#9]
nlp = zh_core_web_sm.load()
Traceback (most recent call last):
  File "/Users/gz/anaconda3/envs/tensorflow/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-5a04cf562c06>", line 1, in <module>
    nlp = zh_core_web_sm.load()
  File "/Users/gz/anaconda3/envs/tensorflow/lib/python3.6/site-packages/zh_core_web_sm/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/Users/gz/anaconda3/envs/tensorflow/lib/python3.6/site-packages/spacy/util.py", line 173, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/Users/gz/anaconda3/envs/tensorflow/lib/python3.6/site-packages/spacy/util.py", line 156, in load_model_from_path
    return nlp.from_disk(model_path)
  File "/Users/gz/anaconda3/envs/tensorflow/lib/python3.6/site-packages/spacy/language.py", line 653, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "/Users/gz/anaconda3/envs/tensorflow/lib/python3.6/site-packages/spacy/util.py", line 511, in from_disk
    reader(path / key)
  File "/Users/gz/anaconda3/envs/tensorflow/lib/python3.6/site-packages/spacy/language.py", line 649, in <lambda>
    deserializers[name] = lambda p, proc=proc: proc.from_disk(p, vocab=False)
  File "pipeline.pyx", line 643, in spacy.pipeline.Tagger.from_disk
  File "/Users/gz/anaconda3/envs/tensorflow/lib/python3.6/site-packages/spacy/util.py", line 511, in from_disk
    reader(path / key)
  File "pipeline.pyx", line 625, in spacy.pipeline.Tagger.from_disk.load_model
  File "pipeline.pyx", line 535, in spacy.pipeline.Tagger.Model
  File "/Users/gz/anaconda3/envs/tensorflow/lib/python3.6/site-packages/spacy/_ml.py", line 447, in build_tagger_model

**Comment by howl-anderson** [comment]
Sorry, that's a silly bug, I will fix it recently. Thank you for your report.

**Comment by howl-anderson** [comment]
Sorry for the delay, bug fixed, I already update new version of 2.0.5
